### ISSUE TITLE
Clever mode look not working as intended. password didnt work.

### ISSUE THREAD

**Issue by ghost** [Puntherline/pun_whitelist#2]
Clever mode look not working as intended. password didnt work.

**Comment by Puntherline** [comment]
When the clever mode is on, it will check if you are on the whitelist. If you are on it, you skip the password check, which is great for regular players. If someone is not on the whitelist with clever mode on, they will be asked for the password. Good for an extra security step. In case it's getting stuck on "Please wait..." you can download the most recent build since this has most likely been fixed.

Edit: In case you want to have both, whitelist **and** a password check regardless of the player being on the whitelist, set "UseWhitelist" and "UsePassword" to true and disable the clever mode.

**Comment by Neofliix** [comment]
In our case we were stuck in "Please wait ..."
I just saw your update, I will test this and give you a feedback

**Comment by Neofliix** [comment]
Perfect the problem is solved, thank you very much
